before_script:
- bash ci/docker_install.sh > /dev/null

test:7.2:
  image: php:7.2
  script:
  - phpunit --bootstrap autoload.php --testdox tests

test:7.1:
  image: php:7.1
  script:
  - phpunit --bootstrap autoload.php --testdox tests