before_script:
- bash ci/docker_install.sh > /dev/null

test:7.3:
  image: php:7.3
  script:
  - phpunit --bootstrap autoload.php --testdox tests

test:7.4:
  image: php:7.4
  script:
  - phpunit --bootstrap autoload.php --testdox tests

test:8.0:
  image: php:8.0
  script:
  - phpunit --bootstrap autoload.php --testdox tests