before_script:
- bash ci/docker_install.sh > /dev/null

test:5.6:
  image: php:5.6
  script:
  - phpunit --bootstrap autoload.php --testdox tests

test:7.0:
  image: php:7.0
  script:
  - phpunit --bootstrap autoload.php --testdox tests