<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit

define( 'ROOT_PATH', dirname(__DIR__) . "/easy-type-passwords/src/" );

spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'getparameters' => '/src/assets/php/class/get-parameters.php',
                'passwordgenerator' => '/src/assets/php/class/password-generator.php',
                'wordlistparser' => '/src/assets/php/class/wordlist-parser.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
